title: "Slick"
description: "Scala Language-Integrated Connection Kit"
markdown: kramdown

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
plugins:
  - jekyll-redirect-from
